import {
  chatEndpoint,
  chatStreamEndpoint,
  graphCharacterEndpoint,
  graphForeshadowsEndpoint,
  graphQueryEndpoint,
  memoryAddEndpoint,
  memorySearchEndpoint,
  memoryTemporalEndpoint,
  memoryUploadEndpoint,
  novelQualityCheckEndpoint,
  wikiListEndpoint,
  wikiPromoteEndpoint,
  wikiReadPageEndpoint,
  workspaceContextEndpoint,
  writingHelperProcessEndpoint,
  writingStreamEndpoint,
  writingCraftAnalyzeEndpoint,
  writingCraftEmotionalArcEndpoint,
  writingCraftVoiceConsistencyEndpoint,
  writingCraftReaderImmersionEndpoint,
  writingCraftPacingNavigatorEndpoint,
  writingCraftLLMEndpoint,
  pluginListEndpoint,
  pluginExecuteEndpoint,
  pluginRegisterEndpoint,
  syncStatusEndpoint,
  syncPushEndpoint,
  syncPullEndpoint,
  syncFullEndpoint,
  foreshadowPlantEndpoint,
  foreshadowStatsEndpoint,
  characterProfileEndpoint,
  characterDepthEndpoint,
  characterRelationshipsEndpoint,
  analysisPatternsEndpoint,
  analysisNarrativeVisualizationEndpoint,
  analysisSessionsEndpoint,
  learningImportEndpoint,
  learningStyleFeedbackEndpoint,
  learningStyleDriftEndpoint,
  learningRulesEndpoint,
  learningReadingSessionEndpoint,
  learningReadingExtractEndpoint,
  learningStatusEndpoint,
  sbGetEntitiesEndpoint,
  sbGetEntityEndpoint,
  sbCreateEntityEndpoint,
  sbUpdateEntityEndpoint,
  sbDeleteEntityEndpoint,
  sbExtractFromManuscriptEndpoint,
  sbGetCompletenessEndpoint,
  qcValidateOutputEndpoint,
  qcGetCreativityConfigEndpoint,
  cwGenerateAutoEndpoint,
  cwGenerateGuidedEndpoint,
  cwGetModesEndpoint,
  cwGetCreativityPresetsEndpoint,
  rsAnalyzeEndpoint,
  rsGetPersonasEndpoint,
  rsCreateCustomPersonaEndpoint,
  rsGetOverlayEndpoint,
} from '../endpoints';
import type { GatewayRoute } from '../gateway-route-types';

export const contentRoutes: GatewayRoute[] = [
  { method: 'POST', pattern: /^\/chat\/stream$/, handler: chatStreamEndpoint },
  { method: 'POST', pattern: /^\/chat$/, handler: chatEndpoint },
  { method: 'POST', pattern: /^\/memory\/search$/, handler: memorySearchEndpoint },
  { method: 'POST', pattern: /^\/memory\/add$/, handler: memoryAddEndpoint },
  { method: 'POST', pattern: /^\/memory\/upload$/, handler: memoryUploadEndpoint },
  { method: 'POST', pattern: /^\/memory\/temporal$/, handler: memoryTemporalEndpoint },
  { method: 'POST', pattern: /^\/workspace\/context$/, handler: workspaceContextEndpoint },
  { method: 'POST', pattern: /^\/graph\/query$/, handler: graphQueryEndpoint },
  { method: 'POST', pattern: /^\/graph\/character$/, handler: graphCharacterEndpoint },
  { method: 'POST', pattern: /^\/graph\/foreshadows$/, handler: graphForeshadowsEndpoint },
  { method: 'POST', pattern: /^\/wiki\/promote$/, handler: wikiPromoteEndpoint },
  { method: 'POST', pattern: /^\/wiki\/list$/, handler: wikiListEndpoint },
  { method: 'POST', pattern: /^\/wiki\/page$/, handler: wikiReadPageEndpoint },
  { method: 'POST', pattern: /^\/writing\/quality$/, handler: novelQualityCheckEndpoint },
  { method: 'POST', pattern: /^\/writing-helper\/process$/, handler: writingHelperProcessEndpoint },
  { method: 'POST', pattern: /^\/writing\/helper$/, handler: writingHelperProcessEndpoint },
  { method: 'POST', pattern: /^\/writing\/stream$/, handler: writingStreamEndpoint },

  // Writing Craft Analysis (M18)
  { method: 'POST', pattern: /^\/writing-craft\/analyze$/, handler: writingCraftAnalyzeEndpoint },
  { method: 'POST', pattern: /^\/writing-craft\/llm-analyze$/, handler: writingCraftLLMEndpoint },
  { method: 'POST', pattern: /^\/writing-craft\/emotional-arc$/, handler: writingCraftEmotionalArcEndpoint },
  { method: 'POST', pattern: /^\/writing-craft\/voice-consistency$/, handler: writingCraftVoiceConsistencyEndpoint },
  { method: 'POST', pattern: /^\/writing-craft\/reader-immersion$/, handler: writingCraftReaderImmersionEndpoint },
  { method: 'POST', pattern: /^\/writing-craft\/pacing-navigator$/, handler: writingCraftPacingNavigatorEndpoint },

  // Plugins (M19)
  { method: 'GET', pattern: /^\/plugins\/list$/, handler: pluginListEndpoint },
  { method: 'POST', pattern: /^\/plugins\/execute$/, handler: pluginExecuteEndpoint },
  { method: 'POST', pattern: /^\/plugins\/register$/, handler: pluginRegisterEndpoint },

  // Sync (M20)
  { method: 'GET', pattern: /^\/sync\/status$/, handler: syncStatusEndpoint },
  { method: 'POST', pattern: /^\/sync\/push$/, handler: syncPushEndpoint },
  { method: 'POST', pattern: /^\/sync\/pull$/, handler: syncPullEndpoint },
  { method: 'POST', pattern: /^\/sync\/full$/, handler: syncFullEndpoint },

  // Foreshadow CRUD
  { method: 'POST', pattern: /^\/foreshadow\/plant$/, handler: foreshadowPlantEndpoint },
  { method: 'GET', pattern: /^\/foreshadow\/stats$/, handler: foreshadowStatsEndpoint },

  // Character analysis
  { method: 'POST', pattern: /^\/character\/profile$/, handler: characterProfileEndpoint },
  { method: 'POST', pattern: /^\/character\/depth$/, handler: characterDepthEndpoint },
  { method: 'POST', pattern: /^\/character\/relationships$/, handler: characterRelationshipsEndpoint },

  // Analysis
  { method: 'POST', pattern: /^\/analysis\/patterns$/, handler: analysisPatternsEndpoint },
  { method: 'POST', pattern: /^\/analysis\/sessions$/, handler: analysisSessionsEndpoint },
  { method: 'POST', pattern: /^\/analysis\/narrative-visualization$/, handler: analysisNarrativeVisualizationEndpoint },

  // Learning (M22)
  { method: 'POST', pattern: /^\/learning\/import$/, handler: learningImportEndpoint },
  { method: 'POST', pattern: /^\/learning\/style-feedback$/, handler: learningStyleFeedbackEndpoint },
  { method: 'POST', pattern: /^\/learning\/style-drift$/, handler: learningStyleDriftEndpoint },
  { method: 'GET', pattern: /^\/learning\/rules$/, handler: learningRulesEndpoint },
  { method: 'POST', pattern: /^\/learning\/reading-session$/, handler: learningReadingSessionEndpoint },
  { method: 'POST', pattern: /^\/learning\/reading-extract$/, handler: learningReadingExtractEndpoint },
  { method: 'GET', pattern: /^\/learning\/status$/, handler: learningStatusEndpoint },

  // Story Bible CRUD (T-010)
  { method: 'POST', pattern: /^\/story-bible\/entities\/list$/, handler: sbGetEntitiesEndpoint },
  { method: 'GET', pattern: /^\/story-bible\/entity\/([^/]+)$/, handler: sbGetEntityEndpoint, paramNames: ['entityId'] },
  { method: 'POST', pattern: /^\/story-bible\/entities$/, handler: sbCreateEntityEndpoint },
  { method: 'PUT', pattern: /^\/story-bible\/entity\/([^/]+)$/, handler: sbUpdateEntityEndpoint, paramNames: ['entityId'] },
  { method: 'DELETE', pattern: /^\/story-bible\/entity\/([^/]+)$/, handler: sbDeleteEntityEndpoint, paramNames: ['entityId'] },
  { method: 'POST', pattern: /^\/story-bible\/extract$/, handler: sbExtractFromManuscriptEndpoint },
  { method: 'POST', pattern: /^\/story-bible\/completeness$/, handler: sbGetCompletenessEndpoint },

  // Quality Control (T-010)
  { method: 'POST', pattern: /^\/qc\/validate$/, handler: qcValidateOutputEndpoint },
  { method: 'POST', pattern: /^\/qc\/creativity-config$/, handler: qcGetCreativityConfigEndpoint },

  // Co-Writing Engine (T-020)
  { method: 'POST', pattern: /^\/cowriting\/generate\/auto$/, handler: cwGenerateAutoEndpoint },
  { method: 'POST', pattern: /^\/cowriting\/generate\/guided$/, handler: cwGenerateGuidedEndpoint },
  { method: 'GET', pattern: /^\/cowriting\/modes$/, handler: cwGetModesEndpoint },
  { method: 'GET', pattern: /^\/cowriting\/creativity-presets$/, handler: cwGetCreativityPresetsEndpoint },

  // Reader Simulation (T-036)
  { method: 'POST', pattern: /^\/reader\/analyze$/, handler: rsAnalyzeEndpoint },
  { method: 'GET', pattern: /^\/reader\/personas$/, handler: rsGetPersonasEndpoint },
  { method: 'POST', pattern: /^\/reader\/personas\/custom$/, handler: rsCreateCustomPersonaEndpoint },
  { method: 'POST', pattern: /^\/reader\/overlay$/, handler: rsGetOverlayEndpoint },
];
