import {
  checkpointCreateEndpoint,
  checkpointListEndpoint,
  checkpointRestoreEndpoint,
  uiBridgeWorkflowExecuteEndpoint,
  uiBridgeWorkflowLifecycleEndpoint,
  uiBridgeWorkflowPlanEndpoint,
  uiBridgeWorkflowRouteEndpoint,
  uiBridgeWorkflowSchedulerImportLitePlanEndpoint,
  uiBridgeWorkflowSchedulerListEndpoint,
  uiBridgeWorkflowSchedulerPauseEndpoint,
  uiBridgeWorkflowSchedulerRegisterEndpoint,
  uiBridgeWorkflowSchedulerResumeEndpoint,
  uiBridgeWorkflowSchedulerRunNowEndpoint,
  workflowExecuteEndpoint,
  workflowLifecycleEndpoint,
  workflowPlanEndpoint,
  workflowQuickRollbackEndpoint,
  workflowRevisionStartSessionEndpoint,
  workflowRevisionAnalyzeEndpoint,
  workflowRevisionSuggestEndpoint,
  workflowRevisionMarkRevisedEndpoint,
  workflowRevisionCompareEndpoint,
  workflowRevisionHistoryEndpoint,
  workflowRouteEndpoint,
  workflowSchedulerImportLitePlanEndpoint,
  workflowSchedulerListEndpoint,
  workflowSchedulerPauseEndpoint,
  workflowSchedulerRegisterEndpoint,
  workflowSchedulerResumeEndpoint,
  workflowSchedulerRunNowEndpoint,
} from '../endpoints';
import type { GatewayRoute } from '../gateway-route-types';

export const workflowRoutes: GatewayRoute[] = [
  { method: 'POST', pattern: /^\/workflow\/route$/, handler: workflowRouteEndpoint },
  { method: 'POST', pattern: /^\/workflow\/plan$/, handler: workflowPlanEndpoint },
  { method: 'POST', pattern: /^\/workflow\/execute$/, handler: workflowExecuteEndpoint },
  { method: 'POST', pattern: /^\/workflow\/lifecycle$/, handler: workflowLifecycleEndpoint },
  { method: 'POST', pattern: /^\/workflow\/rollback$/, handler: workflowQuickRollbackEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/start-session$/, handler: workflowRevisionStartSessionEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/analyze$/, handler: workflowRevisionAnalyzeEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/suggest$/, handler: workflowRevisionSuggestEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/mark-revised$/, handler: workflowRevisionMarkRevisedEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/compare$/, handler: workflowRevisionCompareEndpoint },
  { method: 'POST', pattern: /^\/workflow\/revision\/history$/, handler: workflowRevisionHistoryEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/register$/, handler: workflowSchedulerRegisterEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/list$/, handler: workflowSchedulerListEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/pause$/, handler: workflowSchedulerPauseEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/resume$/, handler: workflowSchedulerResumeEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/run-now$/, handler: workflowSchedulerRunNowEndpoint },
  { method: 'POST', pattern: /^\/workflow\/scheduler\/import-lite-plan$/, handler: workflowSchedulerImportLitePlanEndpoint },
  { method: 'POST', pattern: /^\/checkpoint\/create$/, handler: checkpointCreateEndpoint },
  { method: 'POST', pattern: /^\/checkpoint\/restore$/, handler: checkpointRestoreEndpoint },
  { method: 'POST', pattern: /^\/checkpoint\/list$/, handler: checkpointListEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/route$/, handler: uiBridgeWorkflowRouteEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/plan$/, handler: uiBridgeWorkflowPlanEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/execute$/, handler: uiBridgeWorkflowExecuteEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/lifecycle$/, handler: uiBridgeWorkflowLifecycleEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/register$/, handler: uiBridgeWorkflowSchedulerRegisterEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/list$/, handler: uiBridgeWorkflowSchedulerListEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/pause$/, handler: uiBridgeWorkflowSchedulerPauseEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/resume$/, handler: uiBridgeWorkflowSchedulerResumeEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/run-now$/, handler: uiBridgeWorkflowSchedulerRunNowEndpoint },
  { method: 'POST', pattern: /^\/ui-bridge\/workflow\/scheduler\/import-lite-plan$/, handler: uiBridgeWorkflowSchedulerImportLitePlanEndpoint },
];
