import type { Template, TemplatePlaceholder } from '../types/template'

const ph = (name: string, label: string, defaultValue: string, type: TemplatePlaceholder['type'] = 'text', options?: string[]): TemplatePlaceholder => ({
  name, label, defaultValue, type, options,
})

export const threeActOutline: Template = {
  id: 'builtin-plot-three-act',
  title: '三幕结构大纲',
  description: '经典三幕结构的情节大纲模板：建置、对抗、结局',
  category: 'plot',
  content: {
    type: 'doc',
    content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '{{story_title}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '第一幕：建置' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '触发事件：{{inciting_event}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '核心冲突：{{central_conflict}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '第二幕：对抗' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '情节升级：{{rising_action}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '中点转折：{{midpoint_turn}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '至暗时刻：{{darkest_moment}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '第三幕：结局' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '高潮对决：{{climax}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '收尾与回响：{{resolution}}' }] },
    ],
  },
  placeholders: [
    ph('story_title', '故事标题', '未命名故事'),
    ph('inciting_event', '触发事件', '主角遭遇改变命运的突发事件...'),
    ph('central_conflict', '核心冲突', '主角面临的核心矛盾与抉择...'),
    ph('rising_action', '情节升级', '冲突逐步升级的关键节点...'),
    ph('midpoint_turn', '中点转折', '故事走向发生根本性转变的时刻...'),
    ph('darkest_moment', '至暗时刻', '主角陷入绝境的最低点...'),
    ph('climax', '高潮对决', '最终冲突的爆发与解决...'),
    ph('resolution', '收尾与回响', '故事结局与主题回响...'),
  ],
  isBuiltIn: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}

export const heroJourneyOutline: Template = {
  id: 'builtin-plot-hero-journey',
  title: '英雄之旅大纲',
  description: '基于约瑟夫·坎贝尔英雄之旅理论的情节发展模板',
  category: 'plot',
  content: {
    type: 'doc',
    content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '{{story_title}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '启程' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '平凡世界：{{ordinary_world}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '冒险召唤：{{call_to_adventure}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '跨越门槛：{{crossing_threshold}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '启蒙' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '试炼之路：{{road_of_trials}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '盟友与敌人：{{allies_and_enemies}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '深渊考验：{{abyss_ordeal}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '归来' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '终极恩赐：{{ultimate_boon}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '拒绝回归：{{refusal_to_return}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '携宝还乡：{{return_with_elixir}}' }] },
    ],
  },
  placeholders: [
    ph('story_title', '故事标题', '未命名故事'),
    ph('ordinary_world', '平凡世界', '主角日常生活状态的描写...'),
    ph('call_to_adventure', '冒险召唤', '打破平静的事件或邀请...'),
    ph('crossing_threshold', '跨越门槛', '主角正式踏上冒险旅程...'),
    ph('road_of_trials', '试炼之路', '主角面临的一系列挑战...'),
    ph('allies_and_enemies', '盟友与敌人', '旅途中结识的伙伴与对手...'),
    ph('abyss_ordeal', '深渊考验', '最严峻的考验与生死危机...'),
    ph('ultimate_boon', '终极恩赐', '主角获得的最终收获或领悟...'),
    ph('refusal_to_return', '拒绝回归', '主角对回归常态的犹豫...'),
    ph('return_with_elixir', '携宝还乡', '主角带着收获回归并改变周遭...'),
  ],
  isBuiltIn: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}

export const mysteryClueWeb: Template = {
  id: 'builtin-plot-mystery-clue',
  title: '悬疑线索网',
  description: '悬疑推理小说的线索布局与误导设计模板',
  category: 'plot',
  content: {
    type: 'doc',
    content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '{{case_title}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '核心谜题' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '谜面：{{mystery_premise}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '真相：{{truth}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '线索布局' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '显性线索：{{obvious_clues}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '隐性线索：{{hidden_clues}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '红鲱鱼（误导）：{{red_herrings}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '嫌疑人' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '{{suspects}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '解谜节点' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '{{revelation_points}}' }] },
    ],
  },
  placeholders: [
    ph('case_title', '案件名称', '未命名案件'),
    ph('mystery_premise', '谜面', '表面上呈现的谜团...'),
    ph('truth', '真相', '隐藏在表象之下的真实...'),
    ph('obvious_clues', '显性线索', '读者和角色都能注意到的线索...'),
    ph('hidden_clues', '隐性线索', '需要仔细推敲才能发现的线索...'),
    ph('red_herrings', '红鲱鱼（误导）', '故意设置的误导信息...'),
    ph('suspects', '嫌疑人列表', '各嫌疑人的动机与不在场证明...'),
    ph('revelation_points', '解谜节点', '真相逐步揭示的关键时刻...'),
  ],
  isBuiltIn: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}

export const conflictEscalation: Template = {
  id: 'builtin-plot-conflict-escalation',
  title: '冲突升级表',
  description: '系统化设计冲突从萌芽到爆发的升级路径',
  category: 'plot',
  content: {
    type: 'doc',
    content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '{{conflict_name}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '冲突双方' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '甲方：{{party_a}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '乙方：{{party_b}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '升级阶段' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '第一阶段（潜伏）：{{stage_1}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '第二阶段（摩擦）：{{stage_2}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '第三阶段（对抗）：{{stage_3}}' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '第四阶段（爆发）：{{stage_4}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '冲突根源' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '{{root_cause}}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '解决或结局' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '{{resolution}}' }] },
    ],
  },
  placeholders: [
    ph('conflict_name', '冲突名称', '核心冲突'),
    ph('party_a', '甲方', '冲突的一方及其立场...'),
    ph('party_b', '乙方', '冲突的另一方及其立场...'),
    ph('stage_1', '第一阶段（潜伏）', '矛盾暗流涌动，尚未表面化...'),
    ph('stage_2', '第二阶段（摩擦）', '小摩擦不断，关系紧张...'),
    ph('stage_3', '第三阶段（对抗）', '正面冲突，立场对立...'),
    ph('stage_4', '第四阶段（爆发）', '冲突达到顶点，不可调和...'),
    ph('root_cause', '冲突根源', '导致冲突的深层原因...'),
    ph('resolution', '解决或结局', '冲突的最终走向...'),
  ],
  isBuiltIn: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}

export const PLOT_BUILTINS: Template[] = [
  threeActOutline,
  heroJourneyOutline,
  mysteryClueWeb,
  conflictEscalation,
]
