import { defineConfig, mergeConfig } from 'vitest/config';

import baseConfig from './vitest.config';

export default mergeConfig(
  baseConfig,
  defineConfig({
    test: {
      coverage: {
        provider: 'v8',
        reporter: ['text', 'json', 'html'],
        include: [
          'agents/index.ts',
          'agents/base.ts',
          'agents/architect.ts',
          'agents/commander.ts',
          'agents/critic.ts',
          'agents/character.ts',
          'agents/factory.ts',
          'agents/plot.ts',
          'agents/sequential-thinking.ts',
          'agents/skill-router.ts',
          'agents/worldbuilding.ts',
          'agents/writer.ts',
          'container/adapters.ts',
          'mcp/services/workflow.ts',
          'mcp/services/critic.ts',
          'mcp/endpoints/workflow.ts',
          'workflow/workflow-engine.ts',
          'workflow/graph.ts',
          'workflow/base-workflow.ts',
          'workflow/state.ts',
          'workflow/types.ts',
          'workflow/project-tech.ts',
          'workflow/graph-factory.ts',
          'workflow/novel-quality.ts',
          'workflow/novel-state.ts',
          'workflow/modes/plan-act.ts',
          'workflow/revision-loop.ts',
          'workflow/session/session-manager.ts',
          'workflow/adapters/code-adapter.ts',
          'workflow/session/resume-strategy.ts',
          'workflow/levels/level1-rapid.ts',
          'workflow/levels/level2-lite.ts',
          'workflow/levels/level3-standard.ts',
          'workflow/levels/level5-coordinator.ts',
          'workflow/levels/level4-brainstorm.ts',
          'workflow/levels/base-level.ts',
          'workflow/adapters/base-adapter.ts',
          'workflow/adapters/novel-adapter.ts',
          'workflow/index.ts',
          'narrative/evaluators/base.ts',
          'narrative/evaluators/character-evaluator.ts',
          'narrative/evaluators/cliche-detector.ts',
          'narrative/evaluators/four-selves-evaluator.ts',
          'narrative/evaluators/dream-evaluator.ts',
          'narrative/evaluators/suspense-evaluator.ts',
          'narrative/evaluators/deadly-sins-checker.ts',
          'narrative/evaluators/pyramid-evaluator.ts',
          'narrative/evaluators/subtext-evaluator.ts',
          'narrative/evaluators/premise-evaluator.ts',
          'narrative/evaluators/voice-evaluator.ts',
          'narrative/evaluators/critic-engine.ts',
          'narrative/index.ts',
          'narrative/foreshadowing.ts',
          'narrative/narrative-voice.ts',
          'narrative/premise-validator.ts',
          'narrative/character-depth.ts',
          'narrative/types.ts',
          'narrative/scene-coherence.ts',
          'narrative/suspense-analyzer.ts',
          'narrative/style-system.ts',
          'narrative/fictional_dream/index.ts',
          'narrative/fictional_dream/sympathy.ts',
          'narrative/fictional_dream/engine.ts',
          'narrative/fictional_dream/evaluator.ts',
          'narrative/fictional_dream/identification.ts',
          'narrative/fictional_dream/empathy.ts',
          'narrative/fictional_dream/immersion.ts',
          'narrative/analyzers/base.ts',
          'narrative/analyzers/index.ts',
          'narrative/analyzers/sensory-analyzer.ts',
          'narrative/analyzers/conflict-analyzer.ts',
          'narrative/analyzers/character-state-analyzer.ts',
          'narrative/analyzers/tension-curve-analyzer.ts',
          'narrative/evaluators/index.ts',
          'narrative/character-manager.ts',
        ],
        thresholds: {
          lines: 75,
          branches: 55,
          functions: 69,
          statements: 75,
        },
      },
    },
  }),
);
