import { mergeConfig, type UserConfig } from 'vitest/config';

import { baseVitestConfig } from './vitest.config';

// Phase 3 test discovery is config-driven (single source of truth).
// Adding a new phase3 test? Add its path here — no package.json edit needed.
const phase3TestFiles: string[] = [
  // workflow/* (22)
  'tests/workflow/level5-coordinator.test.ts',
  'tests/workflow/novel-adapter.test.ts',
  'tests/workflow/workflow-types.test.ts',
  'tests/workflow/project-tech.test.ts',
  'tests/workflow/graph-factory.test.ts',
  'tests/workflow/resume-strategy.test.ts',
  'tests/workflow/revision-loop.test.ts',
  'tests/workflow/level4-brainstorm.test.ts',
  'tests/workflow/graph.test.ts',
  'tests/workflow/plan-act.test.ts',
  'tests/workflow/level1-rapid.test.ts',
  'tests/workflow/level2-lite.test.ts',
  'tests/workflow/level3-standard.test.ts',
  'tests/workflow/code-adapter.test.ts',
  'tests/workflow/state.test.ts',
  'tests/workflow/novel-quality.test.ts',
  'tests/workflow/session-manager.test.ts',
  'tests/workflow/base-workflow.test.ts',
  'tests/workflow/novel-state.test.ts',
  'tests/workflow/base-adapter.test.ts',
  'tests/workflow/base-level.test.ts',
  'tests/workflow/index.test.ts',
  // agents/* (12)
  'tests/agents/base.test.ts',
  'tests/agents/architect.test.ts',
  'tests/agents/commander.test.ts',
  'tests/agents/critic.test.ts',
  'tests/agents/writer.test.ts',
  'tests/agents/skill-router.test.ts',
  'tests/agents/sequential-thinking.test.ts',
  'tests/agents/factory.test.ts',
  'tests/agents/plot.test.ts',
  'tests/agents/character.test.ts',
  'tests/agents/worldbuilding.test.ts',
  'tests/agents/index.test.ts',
  // container/* (3) + workflow integration (1)
  'tests/container/search-engine-adapter.test.ts',
  'tests/container/search-engine-integration.test.ts',
  'tests/container/critic-engine-adapter.test.ts',
  'tests/workflow/workflow-engine.integration.test.ts',
  'tests/container/workflow-engine-adapter.test.ts',
  // mcp/* (4)
  'tests/mcp/workflow-service.test.ts',
  'tests/mcp/workflow-endpoints.integration.test.ts',
  'tests/mcp/critic-service.test.ts',
  'tests/mcp/workflow-critic-smoke.integration.test.ts',
  // narrative/* (38)
  'tests/narrative/critic-engine.quickscan.test.ts',
  'tests/narrative/foreshadowing.test.ts',
  'tests/narrative/scene-coherence.test.ts',
  'tests/narrative/conflict-analyzer.test.ts',
  'tests/narrative/character-manager.test.ts',
  'tests/narrative/character-state-analyzer.test.ts',
  'tests/narrative/tension-curve-analyzer.test.ts',
  'tests/narrative/sensory-analyzer.test.ts',
  'tests/narrative/suspense-analyzer.test.ts',
  'tests/narrative/style-system.test.ts',
  'tests/narrative/narrative-voice.test.ts',
  'tests/narrative/premise-validator.test.ts',
  'tests/narrative/types.test.ts',
  'tests/narrative/analyzers-index.test.ts',
  'tests/narrative/evaluators-index.test.ts',
  'tests/narrative/index.test.ts',
  'tests/narrative/fictional-dream-index.test.ts',
  'tests/narrative/character-depth.test.ts',
  'tests/narrative/fictional-dream-sympathy.test.ts',
  'tests/narrative/fictional-dream-engine.test.ts',
  'tests/narrative/fictional-dream-evaluator.test.ts',
  'tests/narrative/fictional-dream-identification.test.ts',
  'tests/narrative/fictional-dream-empathy.test.ts',
  'tests/narrative/fictional-dream-immersion.test.ts',
  'tests/narrative/dream-evaluator.test.ts',
  'tests/narrative/suspense-evaluator.test.ts',
  'tests/narrative/deadly-sins-checker.test.ts',
  'tests/narrative/cliche-detector.test.ts',
  'tests/narrative/four-selves-evaluator.test.ts',
  'tests/narrative/subtext-evaluator.test.ts',
  'tests/narrative/evaluator-base.test.ts',
  'tests/narrative/pyramid-evaluator.test.ts',
  'tests/narrative/critic-engine.test.ts',
  'tests/narrative/analyzers-base.test.ts',
  'tests/narrative/character-evaluator.test.ts',
  'tests/narrative/premise-evaluator.test.ts',
  'tests/narrative/voice-evaluator.test.ts',
];

const phase3Config: UserConfig = {
  test: {
    include: phase3TestFiles,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: [
        'agents/index.ts',
        'agents/base.ts',
        'agents/architect.ts',
        'agents/commander.ts',
        'agents/critic.ts',
        'agents/character.ts',
        'agents/factory.ts',
        'agents/plot.ts',
        'agents/sequential-thinking.ts',
        'agents/skill-router.ts',
        'agents/worldbuilding.ts',
        'agents/writer.ts',
        'container/adapters.ts',
        'mcp/services/workflow.ts',
        'mcp/services/critic.ts',
        'mcp/endpoints/workflow.ts',
        'workflow/workflow-engine.ts',
        'workflow/graph.ts',
        'workflow/base-workflow.ts',
        'workflow/state.ts',
        'workflow/types.ts',
        'workflow/project-tech.ts',
        'workflow/graph-factory.ts',
        'workflow/novel-quality.ts',
        'workflow/novel-state.ts',
        'workflow/modes/plan-act.ts',
        'workflow/revision-loop.ts',
        'workflow/session/session-manager.ts',
        'workflow/adapters/code-adapter.ts',
        'workflow/session/resume-strategy.ts',
        'workflow/levels/level1-rapid.ts',
        'workflow/levels/level2-lite.ts',
        'workflow/levels/level3-standard.ts',
        'workflow/levels/level5-coordinator.ts',
        'workflow/levels/level4-brainstorm.ts',
        'workflow/levels/base-level.ts',
        'workflow/adapters/base-adapter.ts',
        'workflow/adapters/novel-adapter.ts',
        'workflow/index.ts',
        'narrative/evaluators/base.ts',
        'narrative/evaluators/character-evaluator.ts',
        'narrative/evaluators/cliche-detector.ts',
        'narrative/evaluators/four-selves-evaluator.ts',
        'narrative/evaluators/dream-evaluator.ts',
        'narrative/evaluators/suspense-evaluator.ts',
        'narrative/evaluators/deadly-sins-checker.ts',
        'narrative/evaluators/pyramid-evaluator.ts',
        'narrative/evaluators/subtext-evaluator.ts',
        'narrative/evaluators/premise-evaluator.ts',
        'narrative/evaluators/voice-evaluator.ts',
        'narrative/evaluators/critic-engine.ts',
        'narrative/index.ts',
        'narrative/foreshadowing.ts',
        'narrative/narrative-voice.ts',
        'narrative/premise-validator.ts',
        'narrative/character-depth.ts',
        'narrative/types.ts',
        'narrative/scene-coherence.ts',
        'narrative/suspense-analyzer.ts',
        'narrative/style-system.ts',
        'narrative/fictional_dream/index.ts',
        'narrative/fictional_dream/sympathy.ts',
        'narrative/fictional_dream/engine.ts',
        'narrative/fictional_dream/evaluator.ts',
        'narrative/fictional_dream/identification.ts',
        'narrative/fictional_dream/empathy.ts',
        'narrative/fictional_dream/immersion.ts',
        'narrative/analyzers/base.ts',
        'narrative/analyzers/index.ts',
        'narrative/analyzers/sensory-analyzer.ts',
        'narrative/analyzers/conflict-analyzer.ts',
        'narrative/analyzers/character-state-analyzer.ts',
        'narrative/analyzers/tension-curve-analyzer.ts',
        'narrative/evaluators/index.ts',
        'narrative/character-manager.ts',
      ],
      thresholds: {
        lines: 75,
        branches: 55,
        functions: 69,
        statements: 75,
      },
    },
  },
};

export default mergeConfig(baseVitestConfig, phase3Config);
