#!/bin/bash
#
# install-cli-macos.sh - Install nmem CLI on macOS
# Run this script after installing Nowledge Mem.app
#
# Usage:
#   ./install-cli-macos.sh
#
# Or from the app bundle:
#   "/Applications/Nowledge Mem.app/Contents/Resources/_up_/python-standalone/install-cli-macos.sh"
#

set -e

SYMLINK_TARGET="/usr/local/bin/nmem"

echo "Nowledge Mem CLI Installer"
echo "=========================="
echo

# Get the directory where THIS script is located (the python-standalone dir)
# This works whether run directly or via a symlink
SCRIPT_SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SCRIPT_SOURCE" ]; do
    SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)"
    SCRIPT_SOURCE="$(readlink "$SCRIPT_SOURCE")"
    [[ $SCRIPT_SOURCE != /* ]] && SCRIPT_SOURCE="$SCRIPT_DIR/$SCRIPT_SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)"

# The script is in python-standalone, so that's our base
PYTHON_STANDALONE="$SCRIPT_DIR"

# Verify this is the right directory by checking for python
if [ ! -d "$PYTHON_STANDALONE/python" ]; then
    echo "Error: This script must be run from the python-standalone directory"
    echo "Current location: $PYTHON_STANDALONE"
    exit 1
fi

echo "Found installation at: $PYTHON_STANDALONE"

# Verify Python exists
PYTHON_EXEC="$PYTHON_STANDALONE/python/bin/python3"
if [ ! -x "$PYTHON_EXEC" ]; then
    echo "Error: Bundled Python not found at $PYTHON_EXEC"
    exit 1
fi
echo "Found Python at: $PYTHON_EXEC"

# Verify ncli module exists
NCLI_MODULE="$PYTHON_STANDALONE/app/src/nowledge_graph_server/ncli.py"
if [ ! -f "$NCLI_MODULE" ]; then
    echo "Error: CLI module not found at $NCLI_MODULE"
    exit 1
fi
echo "Found CLI module at: $NCLI_MODULE"

# Create the wrapper script with HARDCODED paths (not relative)
# This ensures it works regardless of how it's invoked
WRAPPER_SCRIPT="$PYTHON_STANDALONE/nmem-wrapper"

cat > "$WRAPPER_SCRIPT" << WRAPPER_EOF
#!/bin/bash
# nmem - Nowledge Mem CLI
# Uses bundled Python from the Nowledge Mem installation
# Auto-generated by install-cli-macos.sh

# Hardcoded paths to the bundle (set at install time)
PYTHON_STANDALONE="$PYTHON_STANDALONE"
PYTHON="\$PYTHON_STANDALONE/python/bin/python3"
NCLI="\$PYTHON_STANDALONE/app/src/nowledge_graph_server/ncli.py"

# Verify Python exists
if [ ! -x "\$PYTHON" ]; then
    echo "Error: Bundled Python not found at \$PYTHON" >&2
    echo "The Nowledge Mem app may have been moved or uninstalled." >&2
    exit 1
fi

# Verify ncli module exists
if [ ! -f "\$NCLI" ]; then
    echo "Error: CLI module not found at \$NCLI" >&2
    exit 1
fi

# Set PYTHONPATH for the app modules
APP_SRC="\$PYTHON_STANDALONE/app/src"
export PYTHONPATH="\$APP_SRC:\$PYTHONPATH"

# Set library path for bundled Python (macOS)
export DYLD_LIBRARY_PATH="\$PYTHON_STANDALONE/python/lib:\$DYLD_LIBRARY_PATH"

# Run the CLI
exec "\$PYTHON" "\$NCLI" "\$@"
WRAPPER_EOF

chmod +x "$WRAPPER_SCRIPT"
echo "Created CLI wrapper at: $WRAPPER_SCRIPT"

# Create symlink in /usr/local/bin
if [ ! -d "/usr/local/bin" ]; then
    echo "Creating /usr/local/bin directory..."
    sudo mkdir -p /usr/local/bin
fi

echo
echo "Creating symlink at $SYMLINK_TARGET..."
echo "This requires administrator privileges."
echo

# Remove existing symlink or file if it exists
if [ -e "$SYMLINK_TARGET" ] || [ -L "$SYMLINK_TARGET" ]; then
    sudo rm -f "$SYMLINK_TARGET"
fi

# Create new symlink
sudo ln -sf "$WRAPPER_SCRIPT" "$SYMLINK_TARGET"

echo "✓ Successfully installed nmem CLI!"
echo
echo "You can now use 'nmem' from any terminal:"
echo "  nmem status        - Check if server is running"
echo "  nmem memories      - List recent memories"
echo "  nmem threads       - List recent threads"
echo "  nmem --help        - Show all commands"
echo
echo "Make sure Nowledge Mem is running before using the CLI."
